# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: |
          mvn package
      - name: Push Docker
        run: |
          docker login --username=${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }} registry.cn-shanghai.aliyuncs.com
          docker build . -t registry.cn-shanghai.aliyuncs.com/oleolema/test:latest
          docker push registry.cn-shanghai.aliyuncs.com/oleolema/test:latest
          echo $(docker ps -q)
          docker tag $(docker ps -q) registry.cn-shanghai.aliyuncs.com/oleolema/test:$GITHUB_RUN_ID
          docker push registry.cn-shanghai.aliyuncs.com/oleolema/test:$GITHUB_RUN_ID


  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands pull docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PWD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull registry.cn-shanghai.aliyuncs.com/oleolema/test:latest


#    - name: Script
#      run: |
#        ls
#        pwd
#        apt-get install -y lftp
#        lftp ${{ secrets.HOST }} -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PWD }} --verbose ./target/*.jar .;exit

#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Upload ftp
#        uses: sebastianpopp/ftp-action@releases/v2
#        with:
#          host: ${{ secrets.HOST }}
#          user: ${{ secrets.FTP_USER }}
#          password: ${{ secrets.FTP_PWD }}
#          localDir: "."
#          remoteDir: "."


#    - uses: actions/checkout@v2
#    - name: Upload ftp
#      uses: sebastianpopp/ftp-action@releases/v2
#      with:
#        host: ${{ secrets.HOST }}
#        user: ${{ secrets.FTP_USER }}
#        password: ${{ secrets.FTP_PWD }}
#        localDir: "work"
#        remoteDir: "work"

#    - uses: actions/checkout@master
#      with:
#        fetch-depth: 2
#    - name: FTP-Deploy-Action
#      uses: SamKirkland/FTP-Deploy-Action@3.0.0
#      with:
#        ftp-server: ftp://${{ secrets.HOST }}
#        ftp-username: ${{ secrets.FTP_USER }}
#        ftp-password: ${{ secrets.FTP_PWD }}




